import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { sites } from './schema';
import dotenv from 'dotenv';

dotenv.config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const db = drizzle(pool);

const nswSites = [
  // Sydney / Northern Beaches
  {
    name: 'Long Reef NE',
    slug: 'long-reef-ne',
    region: 'Sydney Northern Beaches',
    launchLat: -33.7425,
    launchLon: 151.3156,
    launchElevation: 30,
    landingLat: -33.7445,
    landingLon: 151.3175,
    idealWindDirection: 45,
    windSectorStart: 20,
    windSectorEnd: 80,
    minWindSpeed: 10,
    minRating: 'PG2',
    requiresSupervision: true,
    description: 'Popular coastal site for hour building. NE facing cliff with beach landing.',
    hazards: 'Sea breeze can strengthen rapidly in summer. Rotor in strong winds.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/long-reef-ne.html',
    weatherStationUrl: 'https://www.flysydney.com.au/weather/long-reef/',
    adminClub: 'SPHGC',
  },
  {
    name: 'Long Reef SE',
    slug: 'long-reef-se',
    region: 'Sydney Northern Beaches',
    launchLat: -33.7430,
    launchLon: 151.3160,
    launchElevation: 30,
    landingLat: -33.7450,
    landingLon: 151.3180,
    idealWindDirection: 135,
    windSectorStart: 110,
    windSectorEnd: 160,
    minWindSpeed: 10,
    minRating: 'PG3',
    requiresRadio: true,
    description: 'SE facing launch at Long Reef. Requires VHF radio for operations south.',
    hazards: 'Southerly busters can arrive quickly. Watch for increasing gusts.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/long-reef-se.html',
    weatherStationUrl: 'https://www.flysydney.com.au/weather/long-reef/',
    adminClub: 'SPHGC',
  },
  {
    name: 'North Long Reef',
    slug: 'north-long-reef',
    region: 'Sydney Northern Beaches',
    launchLat: -33.7400,
    launchLon: 151.3150,
    launchElevation: 35,
    idealWindDirection: 30,
    windSectorStart: 350,
    windSectorEnd: 60,
    minWindSpeed: 12,
    minRating: 'PG4',
    description: 'Northern section of Long Reef. Tide can narrow beach landing significantly.',
    hazards: 'Check tide times. Beach LZ can disappear at high tide.',
    siteGuideUrl: 'https://www.flysydney.com.au/',
    adminClub: 'SPHGC',
  },
  {
    name: 'Cooks Terrace',
    slug: 'cooks-terrace',
    region: 'Sydney Northern Beaches',
    launchLat: -33.7280,
    launchLon: 151.3020,
    launchElevation: 40,
    idealWindDirection: 90,
    windSectorStart: 60,
    windSectorEnd: 120,
    minWindSpeed: 10,
    minRating: 'PG2',
    requiresSupervision: true,
    requiresRadio: true,
    description: 'Coastal cliff park site. PG2 requires direct on-ground supervision and UHF radio.',
    hazards: 'Turbulence from buildings behind. Limited landing options.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/cooks-terrace.html',
    adminClub: 'SPHGC',
  },
  {
    name: 'Warriewood',
    slug: 'warriewood',
    region: 'Sydney Northern Beaches',
    launchLat: -33.6920,
    launchLon: 151.3050,
    launchElevation: 45,
    idealWindDirection: 45,
    windSectorStart: 20,
    windSectorEnd: 70,
    minWindSpeed: 10,
    minRating: 'PG3',
    description: 'NE coastal cliff. Can catch out even experienced pilots.',
    hazards: 'Site catches pilots out - conditions can change rapidly. Assess carefully.',
    siteGuideUrl: 'https://www.flysydney.com.au/',
    adminClub: 'SPHGC',
  },
  {
    name: 'Turimetta',
    slug: 'turimetta',
    region: 'Sydney Northern Beaches',
    launchLat: -33.6850,
    launchLon: 151.3020,
    launchElevation: 50,
    idealWindDirection: 135,
    windSectorStart: 100,
    windSectorEnd: 150,
    minWindSpeed: 10,
    minRating: 'PG4',
    description: 'SE facing coastal site. Tolerates ESE well.',
    hazards: 'Cliff launch requires confident technique. Rocky landing area.',
    siteGuideUrl: 'https://www.flysydney.com.au/',
    adminClub: 'SPHGC',
  },
  {
    name: 'Mona Vale Headland',
    slug: 'mona-vale-headland',
    region: 'Sydney Northern Beaches',
    launchLat: -33.6770,
    launchLon: 151.3100,
    launchElevation: 40,
    idealWindDirection: 170,
    windSectorStart: 150,
    windSectorEnd: 200,
    minWindSpeed: 10,
    minRating: 'PG4',
    description: 'S to SSE facing. Avoid SSW due to rotor from headland.',
    hazards: 'SSW creates dangerous rotor. Do not fly in SSW.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/mona-vale.html',
    adminClub: 'SPHGC',
  },
  {
    name: 'Bungan',
    slug: 'bungan',
    region: 'Sydney Northern Beaches',
    launchLat: -33.6650,
    launchLon: 151.3150,
    launchElevation: 55,
    idealWindDirection: 90,
    windSectorStart: 60,
    windSectorEnd: 120,
    minWindSpeed: 12,
    minRating: 'PG4',
    description: 'E facing coastal cliff. SPHGC administered.',
    hazards: 'Committed launch. Ensure adequate wind before launching.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/bungan.html',
    adminClub: 'SPHGC',
  },
  {
    name: 'Newport',
    slug: 'newport',
    region: 'Sydney Northern Beaches',
    launchLat: -33.6580,
    launchLon: 151.3180,
    launchElevation: 60,
    idealWindDirection: 90,
    windSectorStart: 70,
    windSectorEnd: 110,
    minWindSpeed: 12,
    minRating: 'PG4',
    maxWindSpeedPg4: 18,
    maxWindSpeedPg5: 22,
    description: 'Two sections - lower (PG4) and upper (PG5). E facing.',
    hazards: 'Upper launch is advanced only. Assess conditions at lower launch first.',
    siteGuideUrl: 'https://www.flysydney.com.au/',
    adminClub: 'SPHGC',
  },
  // Illawarra
  {
    name: 'Stanwell Park - Bald Hill',
    slug: 'stanwell-park-bald-hill',
    region: 'Illawarra',
    launchLat: -34.2260,
    launchLon: 151.0140,
    launchElevation: 300,
    landingLat: -34.2310,
    landingLon: 151.0120,
    idealWindDirection: 135,
    windSectorStart: 90,
    windSectorEnd: 180,
    minWindSpeed: 8,
    maxWindSpeedPg2: 12,
    maxWindSpeedPg3: 15,
    maxWindSpeedPg4: 18,
    maxWindSpeedPg5: 22,
    minRating: 'PG4',
    description: 'Iconic Sydney soaring site. Best S to E. 5-15kn ideal for paragliders.',
    hazards: 'Crowded on good days. Strong lift can go OTB. Watch for HG traffic.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/stanwell-park.html',
    adminClub: 'Stanwell Park HG & PG Club',
  },
  {
    name: 'Hill 60',
    slug: 'hill-60',
    region: 'Illawarra',
    launchLat: -34.4820,
    launchLon: 150.9080,
    launchElevation: 60,
    idealWindDirection: 45,
    windSectorStart: 20,
    windSectorEnd: 80,
    minWindSpeed: 10,
    minRating: 'PG2',
    description: 'Summer NE sea breeze site at Port Kembla. Good for beginners.',
    hazards: 'Industrial area nearby. Watch for sea breeze cycles.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/hill-60.html',
    adminClub: 'Illawarra Hang Gliding Club',
  },
  // Newcastle / Lake Macquarie
  {
    name: 'Catherine Hill Bay',
    slug: 'catherine-hill-bay',
    region: 'Newcastle',
    launchLat: -33.1650,
    launchLon: 151.6380,
    launchElevation: 40,
    idealWindDirection: 90,
    windSectorStart: 60,
    windSectorEnd: 120,
    minWindSpeed: 10,
    minRating: 'PG2',
    description: 'Great beginner site. Soarable over 10 knots.',
    hazards: 'Beach landing. Check tide and surf conditions.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/catherine-hill-bay.html',
    adminClub: 'Newcastle HG & PG Club',
  },
  {
    name: 'Moonee Moonee',
    slug: 'moonee-moonee',
    region: 'Newcastle',
    launchLat: -33.2400,
    launchLon: 151.5700,
    launchElevation: 50,
    idealWindDirection: 90,
    windSectorStart: 70,
    windSectorEnd: 120,
    minWindSpeed: 10,
    minRating: 'PG3',
    description: 'Coastal ridge site north of Newcastle.',
    hazards: 'Cliff launch requires good technique.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/moonee.html',
    adminClub: 'Newcastle HG & PG Club',
  },
  {
    name: 'Merewether',
    slug: 'merewether',
    region: 'Newcastle',
    launchLat: -32.9480,
    launchLon: 151.7580,
    launchElevation: 35,
    idealWindDirection: 180,
    windSectorStart: 150,
    windSectorEnd: 210,
    minWindSpeed: 10,
    minRating: 'PG2',
    requiresSupervision: true,
    description: 'South face PG2 (supervised), East face PG3. Soarable over 10kn.',
    hazards: 'Restricted flying north of Hickson St. Check site guide.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/merewether.html',
    adminClub: 'Newcastle HG & PG Club',
  },
  {
    name: 'Strzelecki Lookout',
    slug: 'strzelecki-lookout',
    region: 'Newcastle',
    launchLat: -33.0500,
    launchLon: 151.6450,
    launchElevation: 80,
    idealWindDirection: 90,
    windSectorStart: 60,
    windSectorEnd: 120,
    minWindSpeed: 10,
    minRating: 'PG3',
    description: 'HG intermediate / PG3 site. Good coastal ridge.',
    hazards: 'Check for HG traffic. Shared launch.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/strzelecki.html',
    adminClub: 'Newcastle HG & PG Club',
  },
  // Mid North Coast
  {
    name: 'Harrys Lookout',
    slug: 'harrys-lookout',
    region: 'Mid North Coast',
    launchLat: -31.4450,
    launchLon: 152.9250,
    launchElevation: 45,
    idealWindDirection: 80,
    windSectorStart: 50,
    windSectorEnd: 110,
    minWindSpeed: 10,
    minRating: 'PG3',
    description: 'Port Macquarie coastal site. ENE to ESE. If unsure DO NOT FLY.',
    hazards: 'Club briefing emphasizes: if unsure, do not fly.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/harrys-lookout.html',
    adminClub: 'Port Macquarie HG & PG Club',
  },
  {
    name: 'Grants Headland - SE Bonnys',
    slug: 'grants-headland',
    region: 'Mid North Coast',
    launchLat: -31.4320,
    launchLon: 152.9380,
    launchElevation: 40,
    idealWindDirection: 120,
    windSectorStart: 90,
    windSectorEnd: 150,
    minWindSpeed: 10,
    minRating: 'PG3',
    description: 'E to SE coastal dune site near Port Macquarie.',
    hazards: 'Dune soaring. Watch for tourists.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/grants-headland.html',
    adminClub: 'Port Macquarie HG & PG Club',
  },
  {
    name: 'North Brother Lookout',
    slug: 'north-brother-lookout',
    region: 'Mid North Coast',
    launchLat: -31.6450,
    launchLon: 152.8200,
    launchElevation: 480,
    idealWindDirection: 90,
    windSectorStart: 60,
    windSectorEnd: 120,
    minWindSpeed: 8,
    minRating: 'PG4',
    requiresInduction: true,
    description: 'Laurieton mountain site. Under PG4 contact local CFI.',
    hazards: 'Mountain flying. Thermic. Contact CFI before first flight.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/north-brother.html',
    adminClub: 'Port Macquarie HG & PG Club',
  },
  // Far North Coast
  {
    name: 'Lennox Head',
    slug: 'lennox-head',
    region: 'Far North Coast',
    launchLat: -28.7870,
    launchLon: 153.5950,
    launchElevation: 50,
    idealWindDirection: 90,
    windSectorStart: 50,
    windSectorEnd: 130,
    minWindSpeed: 10,
    minRating: 'PG4',
    requiresInduction: true,
    requiresSupervision: true,
    description: 'Famous coastal site. PG2/PG3 require induction and supervision.',
    hazards: 'Crowded. Strict operational requirements. Must complete induction.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/lennox-head.html',
    adminClub: 'Byron Bay HG Club',
  },
  {
    name: 'Broadwater National Park',
    slug: 'broadwater-national-park',
    region: 'Far North Coast',
    launchLat: -29.0650,
    launchLon: 153.4350,
    launchElevation: 30,
    idealWindDirection: 90,
    windSectorStart: 60,
    windSectorEnd: 120,
    minWindSpeed: 10,
    minRating: 'PG4',
    requiresInduction: true,
    requiresRadio: true,
    description: 'National Park site. Mandatory radios, NOTAM checks, induction. NPWS consent required.',
    hazards: 'National Park rules apply strictly. Must have completed induction.',
    siteGuideUrl: 'https://www.siteguide.org.au/Sites/broadwater.html',
    adminClub: 'Byron Bay HG Club',
  },
];

async function seed() {
  console.log('Seeding NSW sites...');
  
  for (const site of nswSites) {
    await db.insert(sites).values(site).onConflictDoNothing();
    console.log(`  ✓ ${site.name}`);
  }
  
  console.log(`\nSeeded ${nswSites.length} sites successfully!`);
  await pool.end();
}

seed().catch(console.error);
